### PR TITLE
Expand New Issue Template behavior

### PR DESCRIPTION
**Pull request by Jaxelr**
## Description

First of all, my apologies for not creating an issue with this PR, since i found it brief and concise. I took the liberty of adding committing an example of the newer issue templates in case you are interested in using this feature. If you're not feel free to change the wording or close this PR without merging and you''ll get 0 complaints from my part.

Here's an example of how the New Issue would look with this change. 

image

## Checklist
Please ensure your pull request fulfills the following requirements:
- [x] The commit messages follow our guidelines ([CONTRIBUTING.md](./CONTRIBUTING.md)).
- [ ] Tests for any changes have been added (for bug fixes / features).
- [ ] Docs have been added / updated (for bug fixes / features).

## Type
What kind of change does this pull request introduce?

- [ ] Bug.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Build related changes.
- [ ] CI related changes.
- [x] Documentation content changes.
- [ ] Other (please describe below).

## Breaking Changes
Does this pull request introduce any breaking changes?

- [ ] Yes
- [ ] No

## Other Information

n/a

### CODE REVIEW

**Comment by justinlettau** [comment]
Thanks! I like this feature 👍 I'm gonna play with the templates a bit and i'll add them when i'm done.

**Comment by justinlettau** [comment]
Sorry, I haven't gotten to this yet. Reopening to make sure I don't forget about it 😄

**Comment by justinlettau** [comment]
Thanks for this suggestion @Jaxelr! I've got the first draft implemented.

**Comment by Jaxelr** [comment]
Excellent, hope it helps

**Pull request closed without merging**
