### PR TITLE
Enable user-defined table-valued parameters 

### PR DESCRIPTION
**Pull request by hervetran**
## Description

Small changes that allow user-defined table-valued parameters extractions.

## Checklist
Please ensure your pull request fulfills the following requirements:

- [ ] The commit messages follow our guidelines ([CONTRIBUTING.md](./CONTRIBUTING.md)).
- [ ] Tests for any changes have been added (for bug fixes / features).
- [ ] Docs have been added / updated (for bug fixes / features).

## Type
What kind of change does this pull request introduce?

```
[ ] Bug.
[x] Feature.
[ ] Code style update (formatting, local variables).
[ ] Refactoring (no functional changes, no api changes).
[ ] Build related changes.
[ ] CI related changes.
[x] Documentation content changes.
[ ] Other (please describe below).
```

## Breaking Changes
Does this pull request introduce any breaking changes?

```
[ ] Yes
[x] No
```

## Other Information

n/a

### CODE REVIEW

**Comment by justinlettau** [comment]
@hervetran Hey, this looked pretty good. Any particular reason why you closed it? Thanks.

**Comment by hervetran** [comment]
Hi justin! Glad you liked it, i'm gonna reopen it :)

**Comment by hervetran** [comment]
@justinlettau Don't merge the last commit ( da24928 ) :)

**Comment by justinlettau** [comment]
Closed via [#16](https://github.com/justinlettau/sql-source-control/pull/16).

**Pull request closed without merging**
